### ISSUE TITLE
Scanning of a QR code doesn't work anymore

### ISSUE THREAD

**Issue by bcsti** [zaneschepke/wgtunnel#28] opened 2023-09-20 14:59 UTC
I have tested this behavior on three different devices. If I click on "add Tunnel from QR-Code", a error message stating "invalid QR-Code" appears even though the camera has not yet been started.

**Comment by zaneschepke** [comment] 2023-09-20 15:02
> I have tested this behavior on three different devices. If I click on "add Tunnel from QR-Code", a error message stating "invalid QR-Code" appears even though the camera has not yet been started.

Hello! What version is this happening on and on what devices? I recently changed the QR implementation in version 3.0.0 but I have not pushed this version to the stores yet.

**Comment by bcsti** [comment] 2023-09-20 15:05
I tested it with a Pixel 5 and two Xiaomi devices. Currently the version installed is 2.4.5.

**Comment by zaneschepke** [comment] 2023-09-20 15:19
> I tested it with a Pixel 5 and two Xiaomi devices. Currently the version installed is 2.4.5.

Do you have Google Play Services disabled? The implementation of the QR code scanning on 2.4.5 relies on play services to assist with the QR code scanning. In the latest version 3.0.0, I removed this play services dependency and swapped to a fully open source solution. This new version will go live on F-Droid in the next couple days, after which I was planning to release on Google Play.

**Comment by bcsti** [comment] 2023-09-20 15:24
I changed my WG config and wanted to update all of my devices, but the scanning feature didn't work anymore, even though I used to set them up by the code initially. Deleting all app data and reinstalling didn't work either.
In the end I downloaded the config file and had to use my pc to transfer it.
Yes, I have GPlay on all devices and it has already worked earlier.
Interesting is the behavior on a "new" device (my tablet the app never has been installed on), there the QR module started on the first try.

**Comment by zaneschepke** [comment] 2023-09-20 15:35
That is some really bizarre behavior. Thank you for letting me know about it! I double checked and error is coming from the old implementation that is now removed so this should get resolved with the new version. I will keep the issue open for now until the new version drops and you are able to validate that the issue is resolved.

**Closed** 2023-09-24 11:40 UTC
Labels: bug
