### ISSUE TITLE
[BUG] - Problem with app 3.6.1 LOS 21 unreliable, auto tunnel stops connection

### ISSUE THREAD

**Issue by vsatmydynipnet** [zaneschepke/wgtunnel#463] opened 2024-11-26 19:26 UTC
Running LOS21 without Gapps on Fairphone 3+ with 3.6.1. Since 3.6.0 massive problems. Auto Tunnel swtops working, even it connects after leaving the home Wifi. I lost lot of calls to my asterisk @ home because my linphone lost connection over wireguard. Looks like it stops the tunnel, even auto tunnel and the correct tunnel is shown as on. Linphone says no connection. But you do not see it if phone is in your jacket. :-( . A Fix would definitely be cool :-)

Any idea what it can be?

Thank you for this cool peace of software. Really love it.

**Comment by zaneschepke** [comment] 2024-11-27 05:19
Hey! Can you share some of the auto tunnel settings you have enabled? Do you happen to have wildcards enabled? This should be disabled if you are not using it as it requires extra configuraiton.

Any sharing of your settings and a specific use case/issue that I can try t reproduce would be helpful for me to try and get to the bottom of this. Thanks!

**Comment by vsatmydynipnet** [comment] 2024-11-27 10:45
Enclosed the screenshot of the mobile.

**Comment by vsatmydynipnet** [comment] 2024-11-27 10:46
![Screenshot_20240831-123131_LineageOS-Einstellungen cleaned](https://github.com/user-attachments/assets/ee4dd398-d45c-459f-928e-243bc0ccfe22)
![Screenshot_20241127-113034_WG Tunnel cleaned](https://github.com/user-attachments/assets/5d6cbe36-e03d-4cc3-85a6-c80946f71f4f)
![Screenshot_20241127-113041_WG Tunnel cleaned](https://github.com/user-attachments/assets/36e2b150-be72-4d7d-bdc2-bafcf1d9b00c)
![Screenshot_20241127-113110_Einstellungen cleaned](https://github.com/user-attachments/assets/a5fa1619-21d5-4c02-8cb4-45426c49261d)
![Screenshot_20241127-113130_WG Tunnel cleaned](https://github.com/user-attachments/assets/47641e8e-5db6-483d-acb0-9c29c5aee5fb)
![Screenshot_20241127-113301_WG Tunnel cleaned](https://github.com/user-attachments/assets/d0f25136-6acb-4e4e-a61d-0af6338e8c1a)
sorry, first has not worked

**Comment by zaneschepke** [comment] 2024-11-28 05:08
I'm still struggling to understand exactly what is going wrong. Can you describe a very clear scenario of what is going wrong? 

It sounds like you're saying when the app is backgrounded that auto tunnel stops working after a while and is no longer correctly toggling the tunnel when you are changing between mobile data and wifi? Is this correct?

**Comment by vsatmydynipnet** [comment] 2024-11-28 09:30
Thank you for picking up this issue. Yes, correct. E.g. I leave home WIFI, and auto tunneling connects to the VPN.  Starting with this change, my sip client and other stuff is running through VPN. Easer also switches Owntracks into move mode.  

Meanwhile i check every 30 min if I am still connected in the form of opening Linphone and check if it shows connected. If it is orange i open wgtunnel, stop tunnel and auto tunneling and restart auto tunneling. Then it reconnects to the vpn and works again.  I only become aware of this one because I got calls on mobile, that calling the asterisk server with my sip client extension said unreachable. 

And yes, battery exception, background mode all is set.

I have not checked the "use kernel module" even I am rooted because I do not fully understand what this does.

**Comment by cruux13** [comment] 2024-11-29 13:04
same issue, seems like the service does not keep alive. But I had similar issues with Automate Wireguard workflows since I am on android 15 with my Pixel 9. Triple checked every Battery Optimization setting. Should not be an issue.

**Comment by vsatmydynipnet** [comment] 2024-11-30 11:35
I installed and run Kaffee while  driving  so display does not lock itself. What I saw - but that is only from a non developer view - that at least in these 2 situations - does not say these are all -  this can happen:

A)  When I enter my car in the garden the home WLAN  is very poor, so the mobile switches WLAN-LTE-WLAN-LTE sometimes
B) I have 2 areas where the mobile switches fro, LTE to HSDPA or worse and later, when leaving the are it switches back to LTE

In both cases this - not always - happened. Is it possible that wgtunnel does not see the connectivity change and still hangs on an old connection, not more valid and working? For me this looked like that way and resetting things , which more or less builds up a new connection made things working again.

Unsure if this helps, but I thought I post it for your info.

**Comment by zaneschepke** [comment] 2024-12-01 00:29
So I think this is a race condition issue and that is why we see the irregularity. I've added in protections against this which also allowed for the increased speed auto-tunneling. Please give it a try and see if it improves this issue: https://github.com/zaneschepke/wgtunnel/releases/tag/nightly

**Comment by vsatmydynipnet** [comment] 2024-12-02 10:25
Thank you! Will install it and let it run this week.

**Comment by vsatmydynipnet** [comment] 2024-12-03 09:10
I had to go back to 3.6.1. The nightly version has not detected the move to mobile reliable and so there was no tunnel when leaving home wifi.

**Comment by zaneschepke** [comment] 2024-12-09 16:32
Hello! I believe these issues should be fixed in the latest nightly if anyone is able to confirm.

**Comment by vsatmydynipnet** [comment] 2024-12-09 16:38
I will try tomorrow and test it the next days. Thank you!

**Comment by vsatmydynipnet** [comment] 2024-12-10 08:44
Just saw 3.6.2 is out. I assume i better move to this one for testing?

**Comment by zaneschepke** [comment] 2024-12-12 03:57
> 3.6.2 worked fine since yesterday, even through this bad connection zones. Thank you for your work.

Great to hear! 3.6.3 is basically the same as 3.6.2, with a couple of crash fixes. I'm glad the logic changes have improved the reliability. I'll mark this as closed for now, but please let me know if you experience issues and we can reopen.

**Closed by zaneschepke** 2024-12-12 03:57 UTC
Labels: bug
