### ISSUE TITLE
Main menu littel

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#270] opened 2024-07-25 08:02 UTC
**Describe the bug**
The main menu 3.4.7

**Smartphone (please complete the following information):**

- Device: Nvidia Shield 64 bit]
- Android Version: [e.g. Android 11]
- App Version [e.g. 3.4.7]

**To Reproduce**

1. Go to '...main menu
2. Click on you see mobiel photon creen
3. Scroll down to no you can not use it

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment] 2024-07-27 09:20
Hello! 

This issue is caused by disabling landscape mode. I have now reenabled it. 

This should be fixed in the lastest nightly version release (here)[https://github.com/zaneschepke/wgtunnel/releases/tag/nightly].

Once I have some more features/fixes made, I'll cut a new release to fdroid and google play.

**Closed by zaneschepke** 2024-07-27 09:20 UTC
Labels: bug
