### ISSUE TITLE
Active connection even though the vpn is off

### ISSUE THREAD

**Issue by bcsti** [zaneschepke/wgtunnel#14] opened 2023-07-31 09:43 UTC
After the automatic switch from mobile data to the trusted wifi (auto tunneling on) , the vpn is disabled as expected.

But even if the vpn is off, there is still a active wireguard Negotiation between the android device and the router. Therefore the router thinks the client is still connected via vpn even though the switch in the app is off. 

With the official wireguard app, this problem is not existient. After switching the button to off (in the official app), the connection and Negotiation both are disconnected. 

My device is a Pixel 5 with Android 13.

**Comment by bcsti** [comment] 2023-08-03 12:52
Yes, the issue occurs in about 98% of the time on three different devices. With manual switching and auto tunneling disabled the issue does not occur.

**Comment by zaneschepke** [comment] 2023-08-03 14:24
> Yes, the issue occurs in about 98% of the time on three different devices. With manual switching and auto tunneling disabled the issue does not occur.

Thank you for the additional info! I'll take a look.

**Comment by zaneschepke** [comment] 2023-08-03 18:14
> Yes, the issue occurs in about 98% of the time on three different devices. With manual switching and auto tunneling disabled the issue does not occur.

So I just did a few hours of testing and I see what you are talking about where I am still seeing traffic on my WireGuard server despite the VPN being disconnected on my phone.  However, I uninstalled the WG Tunnel app and performed the same test with the official WireGuard app and I am seeing the same behavior. Can you confirm?

**Comment by bcsti** [comment] 2023-08-03 19:03
When the button is disabled manually, the negotiation between my devices and my router on both the official and your app is stopped. The negotiation is kept alive on your app with auto tunneling enabled only.
![Screenshot_20230803-205957~3](https://github.com/zaneschepke/wgtunnel/assets/92046752/a4280961-a85f-48ba-84f1-32fd3efd51a5)

**Comment by zaneschepke** [comment] 2023-08-03 19:21
> When the button is disabled manually, the negotiation between my devices and my router on both the official and your app is stopped. The negotiation is kept alive on your app with auto tunneling enabled only. (after the switch from mobile data to the trusted wifi network ) ![Screenshot_20230803-205957~3](https://user-images.githubusercontent.com/92046752/258211035-a4280961-a85f-48ba-84f1-32fd3efd51a5.png)

I understand that you are seeing this issue only when auto tunneling is controlling when the tunnel is up or down. During my testing to get to the bottom of this, I was testing to see if I could see this same issue even while auto tunneling was disabled. Even while manually controlling the tunnel I was seeing continued negotiation with the wireguard server. Additionally, I was seeing the same behavior when I uninstalled WG Tunnel and installed the official wireguard app. Are you not seeing the same thing?

**Comment by bcsti** [comment] 2023-08-03 19:45
I understand what you mean. No, I see a different behavior on my device. If I stop the VPN manually, following entry is created in my log: "The WireGuard connection to remote station xxx has been disconnected."

After that the device on my firewall is set to the status "inactive" and loses its domain (assigned port on the firewall gets shut down). Moreover the time for the last negotiation stays unchanged.

When I have auto tunneling active and my network switches from LTE to Wifi, the "Button" in your app switches to off and the vpn connection on my android device disconnects. But the connection from the app is still active in the background and still negotiatiates through the assigned open wireguard port in my firewall even though the VPN is off. 

Therefore my firewall thinks the vpn is still connected and no log entry stating the disconnect is created.

**Comment by bcsti** [comment] 2023-08-03 19:47
But this happens not every single time, in about 2% of the time it disconnects as intended. Btw what firewall do you have?

**Comment by zaneschepke** [comment] 2023-08-03 19:48
> But this happens not every single time, in about 2% of the time it disconnects as intended. Btw what firewall do you have?

I have a Firewalla Purple. How about you?

**Comment by bcsti** [comment] 2023-08-03 20:03
I have a Fritzbox. But you are right, chatting on Discord is much easier 🙃. I will join the server shortly.

**Comment by zaneschepke** [comment] 2023-09-20 05:18
@bcsti I wanted to follow up on this one and see if you are okay with closing this one out. It is hard for me to determine if it something specific with the Fritzbox. Currently, I am still unable to reproduce this behavior.

**Comment by bcsti** [comment] 2023-09-20 15:12
Yes, you can close this issue. Even though the issue still appears, I can't find the cause... If I should ever find a solution, I will comment on this issue.

**Closed** 2023-09-21 04:49 UTC
Labels: bug
