### ISSUE TITLE
[BUG] - Create from scratch - autorotate clears all input fields

### ISSUE THREAD

**Issue by munikiel** [zaneschepke/wgtunnel#212] opened 2024-05-13 18:41 UTC
**Describe the bug**

I'm trying to set up a tunnel. Using the painful method (Create from scratch).

So basically this takes quite a while to fill out. You have to type stuff, copy paste stuff, perhaps switch between apps so you can copy from/to a messenger.

Suddenly all input fields are empty. :sweat: All those inputs lost... like tears in the rain...

First time I didn't realize what happened and I started over... second time again... third time... I finally realize this happens when the display rotates. Holding the phone slightly wrong and bam, everything gone. And so I turn off auto-rotate...

**Smartphone (please complete the following information):**

- Device: Google Nexus 6 (shamu)
- Android Version: 11
- App Version 3.4.2

**Expected behavior**

The app should not discard inputs so easily.

This issue also occurs for saved tunnels. Display rotate reverts to last saved state discarding all not-yet-saved edits.

**Comment by zaneschepke** [comment] 2024-05-13 18:52
Hello! So sorry for this issue. I know what the problem is. I'll have a fix for this is the next version.

**Closed** 2024-06-19 03:09 UTC
Labels: bug
