### ISSUE TITLE
Same can't install [BUG] - Problem with app

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#277] opened 2024-07-27 14:00 UTC
**Describe the bug**

**Smartphone (please complete the following information)

- Device: tv Android Nvidia Shield 
- Android Version: 11
- App Version 3.4.8

**To Reproduce**
Error after its install

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment] 2024-07-27 20:50
Can you describe what is happening when you try to install?

**Comment by zaneschepke** [comment] 2024-07-27 20:51
Duplicate of #276

**Closed by zaneschepke** 2024-07-27 20:51 UTC
Labels: bug
