### ISSUE TITLE
[BUG] - Android Auto missing on Exclude list

### ISSUE THREAD

**Issue by QBANIN** [zaneschepke/wgtunnel#180] opened 2024-04-24 15:29 UTC
In opposite to "oririnal" Wireguard app , WG Tunnel doesn't show Android Auto app on Exclude List.

**Comment by genomez** [comment] 2024-04-24 22:26
> In opposite to "oririnal" Wireguard app , WG Tunnel doesn't show Android Auto app on Exclude List.

It shows in my exclude list. I had to add the exclusion to get Android Auto to work. Not sure if it helps, but I'm on an Samsung S24 Ultra.

**Comment by Gothico74** [comment] 2024-04-25 11:46
Must be on your side.
I have it also and on exclude..

**Comment by QBANIN** [comment] 2024-04-25 11:51
> Must be on your side.
> I have it also and on exclude..

Ok, but why?  😎 ![Screenshot_20240425_135001_WG Tunnel.jpg](https://github.com/zaneschepke/wgtunnel/assets/487657/0c03bca1-33c7-4dc6-ac7c-1455c65af45f)

**Comment by Gothico74** [comment] 2024-04-25 14:28
This is a pic how it looks on my crappy phone

![Screenshot_2024-04-25-16-24-35-669_com.zaneschepke.wireguardautotunnel.jpg](https://github.com/zaneschepke/wgtunnel/assets/57674557/0004e26d-3cc7-48a3-80d7-62e97fe93c83)

**Comment by zaneschepke** [comment] 2024-05-03 23:34
The app is querying all installed packages so not sure what else to do on this one. I am unable to reproduce this behavior so it might be something with that device. Please share if you are able to figure out why this is happening, but I'm closing this one for now.

**Closed by zaneschepke** 2024-05-03 23:34 UTC
Labels: bug
