### ISSUE TITLE
Not working with tunneling apps

### ISSUE THREAD

**Issue by krassivb** [zaneschepke/wgtunnel#51] opened 2023-10-31 23:07 UTC
The app is downloaded from the Google play.
2 sites are configured. 

If apps are not tunneled its working.
When apps are included the VPN can't be established (4 apps selected).

The official app is working with the same config and the selected apps are tunneled.

When I remove included app (all apps tunneled) its working.

Tried with import from zip file and manually entered configuration and a reboot.

config:
A trusted SSID is added.
Tunnel on mobile data.
Tunnel on ethernet.

Tried with the default config (nothing selected) still not working. 

"Enable auto-tunneling" setting can't be switched on despite high accuracy android setting: "precise location required".

Xiaomi MI6
Android 9

**Comment by zaneschepke** [comment] 2023-11-01 02:57
Hello! Thank you for using the app. 

Can you confirm the app version you are on? 

If it is not 3.2.0, please update to the latest. 

If this is happening on the latest, I will try to reproduce on my Android 9 emulator.

**Comment by krassivb** [comment] 2023-11-01 08:50
Latest. 3.2.0

**Comment by zaneschepke** [comment] 2023-11-01 10:58
> Latest. 3.2.0

Thank you. I'll try to reproduce on my end.

**Comment by zaneschepke** [comment] 2023-11-05 03:07
@krassivb I found a bug where there is supposed to be a screen explaining that location permission is needed for auto-tunneling to work (as Wi-Fi SSID is access from location information). I am working on a fix for this bug. 

If you turn on location permission for WG Tunnel, auto tunneling should work properly. 

On my emulator, I was unable to reproduce the other issues you are describing with split application tunneling. 

Can you explain the behavior you see when you say the tunnel is not working with split application tunneling enabled?

**Comment by krassivb** [comment] 2023-11-05 11:43
When I try to start a tunnel with some apps selected the result after some time is the tunnel can't be established. And a red sign next to the tunnel.

I can't turn the location permission on. No such option.

I have a lot of apps (840) and the names of the apps are starting with "t","s", "w" letters. So at the the end of the apps list (if this could help in debugging).
The other particularities are magisk and lsposed.

**Comment by zaneschepke** [comment] 2023-11-05 15:54
In your phone settings: Apps > WG Tunnel > Permissions > Location to turn on location. 

Can you send me a copy of your tunnel config with the keys removed? You can send it to my email as well.

**Comment by zaneschepke** [comment] 2023-11-24 02:11
I am closing this issue due to inactivity. If you have any more need of assistance, please reach out to me via email or on Discord.

**Closed by zaneschepke** 2023-11-24 02:11 UTC
