### ISSUE TITLE
[FEATURE] - Use network change boradcasts

### ISSUE THREAD

**Issue by Mynacol** [zaneschepke/wgtunnel#419] opened 2024-10-28 20:42 UTC
**Is your feature request related to a problem? Please describe.**
I'm annoyed that auto-tunnel for untrusted WiFi networks queries the WiFi name periodically every couple of minutes, as seen by the usage of the location permission. And I believe this behavior is also responsible for high battery usage I observed.

**Describe the solution you'd like**
I'm no android developer, but afaik there is a broadcast any app can receive that signals a changed network connection. I propose to use this broadcast receiver where possible to only check the network status for auto-tunnel when needed. That should significantly reduce the background activity and battery usage and avoids periodically using the location permission.

**Describe alternatives you've considered**
Keep the current implementation I guess?

**Additional context**
I guess this is the (not-deprecated) "get notified by the system on network changes" interface I was alluding to: https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback

**Comment by zaneschepke** [comment] 2024-10-29 02:17
Hello! I think this one is a duplicate of #411. Basically, this high better usage was introduced as part of a bug introduced when I added support for rooted phones to be able to query the wifi name from the shell. Unfortunately, as an undesired side effect, it is causing high battery usage on non rooted phones as well. 

I'm working on a fix for this, but it is not connected to how the app get wifi name (as the battery usage problem was not an issue before this latest kernel feature). 

Please track the progress of this issue in #411. 

Thank you for the report!

**Closed by zaneschepke** 2024-10-29 02:17 UTC
Labels: enhancement

**Comment by seidler2547** [comment] 2024-12-02 20:00
I agree with @Mynacol that it is very annoying that the location is queried so often. When my phone is charging, it seems like the location it polled very frequently, every couple of seconds. I previously used "Automate" with the official Wireguard app and it was not polling at all, it just relied on the network changed broadcast and works fine.

**Comment by zaneschepke** [comment] 2024-12-14 18:51
Yeah, I agree this location querying can get annoying. Could you create a new issue requesting this change?
