### ISSUE TITLE
[BUG] - 3.6.0: High battery usage

### ISSUE THREAD

**Issue by Solarunit** [zaneschepke/wgtunnel#437] opened 2024-11-12 02:16 UTC
**Describe the bug**

High battery usage.
wgtunnel is on top of battery usage statistics after a few hours of idle phone usage. While version 3.5.2 was perfect and app was never in the list. 

So 3.6.0 hasn't fixed this issue for me https://github.com/zaneschepke/wgtunnel/issues/411
I think I have to go back to version 3.5.2 again.

**Smartphone (please complete the following information):**

- Android Version: Android 11
- App Version: 3.6.0
- Backend: Userspace

**Expected behavior**
Same battery usage that was in version 3.5.2

**Comment by zaneschepke** [comment] 2024-11-12 02:52
Hello! This is strange because I am no longer able to replicate this issue on 3.6.0. Can you confirm you do not have "wifi name via shell" enabled. 

Also, have you tried restarting your device since upgrading to 3.6.0 to see if that solves the issue?

**Comment by Solarunit** [comment] 2024-11-12 03:29
>Can you confirm you do not have "wifi name via shell" enabled.

I don't remember that I ever enabled this feature. I don't use any auto-settings. 
I am currently on 3.5.2.    


>Also, have you tried restarting your device since upgrading to 3.6.0 to see if that solves the issue?

I haven't. I upgraded from 3.5.2 -> 3.6.0

**Comment by lincolnep** [comment] 2024-11-13 03:59
I am getting the same issue with 3.6.0 I have rebooted the phone to check but still having the issue.

I don't have wifi name via shell enabled

any suggestions for what to check or info I could provide that would help diagnose the issue?

**Comment by zaneschepke** [comment] 2024-11-13 23:23
@lincolnep Can you share your settings and phone android version/model? I'm still having a hard time reproducing.

**Comment by lincolnep** [comment] 2024-11-14 11:49
I have a s24+ with android 14 October security patch.

I have also noticed that 81gb was down loaded by wg tunnel as I down load less then 25gb in a month normally I have a suspicion it is linked to that

**Comment by lincolnep** [comment] 2024-11-14 11:56
Auto tunnel enabled (tunnel on mobile data)
![Screenshot_20241114_195300_WG Tunnel](https://github.com/user-attachments/assets/879f3c9a-7268-4bdc-9daf-c3a9f91a4948)
![Screenshot_20241114_195424_WG Tunnel](https://github.com/user-attachments/assets/b5c2fc66-8ead-474e-b1b7-a0e129b11805)

**Comment by Solarunit** [comment] 2024-11-14 16:09
In my case all those settings were disabled

**Comment by kic68** [comment] 2024-11-14 19:45
I'm also having the high battery usage (42%). Wifi name via shell diasabled. 
S24U.

**Comment by zaneschepke** [comment] 2024-11-15 04:06
Does everyone here have a Samsung? I'm trying to determine if this is a purely Samsung specific issue.

**Comment by zaneschepke** [comment] 2024-11-15 04:07
Also, were all of you using auto-tunneling? Or was this happening even when auto-tunneling is turned off and just the tunnel is active?

**Comment by kic68** [comment] 2024-11-15 06:25
As already stated, yes, on a Samsung S24U.

Auto-tunneling was active for non-home wifi or mobile situations. Two mobile networks active.

The tunnel itself should have been inactive about 90% of the day as I was mostly at home. 

Resulted in 42% of battery usage.

**Comment by eTaurus** [comment] 2024-11-15 15:21
I don't have a Samsung phone. Android 10. Not as high battery consumption in numbers but the phone gets really warm and the battery depletes rapidly on 3.6.0
I'm back on 3.5.2

**Comment by Solarunit** [comment] 2024-11-15 15:47
>Does everyone here have a Samsung? I'm trying to determine if this is a purely Samsung specific issue.

not Samsung specific

>Also, were all of you using auto-tunneling? Or was this happening even when auto-tunneling is turned off and just the tunnel is active?

No, I don't use auto-tunneling and other auto* options.

**Comment by woble** [comment] 2024-11-16 10:21
High battery usage with 3.6.0 here as well. Non rooted Pixel2XL with A11. Auto tunneling on mobile data and off on specific wifi. 3.5.2 is the only version that doesn't drain the battery.

**Comment by Gothico74** [comment] 2024-11-21 08:50
+1

Xiaomi Mi9 A10

After reverting to 3.5.2 Batteryusage from Hero to Zero..

On my A13 Tablet AutoTunnel doesn't work well; service stops or crashes after loosing WiFi Signal. 3.5.2 has no issues

**Comment by Solarunit** [comment] 2024-11-23 01:07
I am ready test this experimental version :+1:

**Comment by zaneschepke** [comment] 2024-11-23 02:15
> I am ready test this experimental version 👍

Thank you! Here it is: https://github.com/zaneschepke/wgtunnel/releases/tag/3.6.0-battery-regression-fix

**Comment by Solarunit** [comment] 2024-11-23 16:30
I am using prerelease-3.6.0 for a couple of hours and looks like it doesn't have a problem. But I am keep testing.

**Comment by zaneschepke** [comment] 2024-11-23 18:14
> I am using prerelease-3.6.0 for a couple of hours and looks like it doesn't have a problem. But I am keep testing.

Are you testing with no auto-tunnel running or with auto-tunnel running?

**Comment by Solarunit** [comment] 2024-11-23 19:35
@zaneschepke auto-tunnel is disabled, I never used auto-tunnel before.

I removed old data from version 3.5.2 and did clean install testing version and importing config from zip file. All settings are default. So far no problems. Looks like local logging was indeed the reason of high battery usage.

**Comment by zaneschepke** [comment] 2024-11-23 19:56
@Solarunit Thank you so much for testing this and getting back with me so quickly!

I think I'll release a new version with local logging disabled be default for now until I can get to the bottom of what is going wrong there. 

Thanks again!

**Comment by zaneschepke** [comment] 2024-11-23 22:50
Going to close this one out for now as it should be fixed in the latest 3.6.1 release with local logging disabled by default.

If using local logging, I recommend you only turn it on to reproduce a bug, provide the logs, and then turn it off again.  

I'll add a separate action for myself to investigate the logging issue.

**Closed by zaneschepke** 2024-11-23 22:50 UTC
Labels: bug
