### ISSUE TITLE
socks5 and http proxy

### ISSUE THREAD

**Issue by essoojay** [zaneschepke/wgtunnel#92] opened 2024-01-19 12:47 UTC
Hi, 

Just asking

Please is it possible to have inbuilt to have socks5 and http proxy built in

user ----> http or socks proxy ----> wgtunnel---->>>out

thank you.

**Comment by zaneschepke** [comment] 2024-01-19 23:48
Hello! I think this one is a duplicate of #87. Please track the progress of this feature there.

**Closed by zaneschepke** 2024-01-19 23:48 UTC
Labels: enhancement
