### ISSUE TITLE
[BUG] - Android app excluded apps does not retain 

### ISSUE THREAD

**Issue by Guruleenyc** [zaneschepke/wgtunnel#480] opened 2024-12-08 18:48 UTC
**Describe the bug**
After setting excluded apps in the tunnel profile and saving, then exiting the app and going back in to add more excluded apps, I find that all the prior excluded apps were removed and it's back to zero. Please have the excluded app save regardless if you exit the app or not after saving the profile.

**Smartphone (please complete the following information):**

- Device: Pixel 9 Pro XL 
- Android Version: Android 15
- App Version latest 

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment] 2024-12-08 19:29
Hello! I'll look into this and see if I can reproduce. Thank you for the report.

**Comment by zaneschepke** [comment] 2024-12-08 19:30
It seems this is a duplicate of #465. I'll mark it as closed and we can track progress in the original ticket.

**Closed by zaneschepke** 2024-12-08 19:30 UTC
Labels: bug
