### ISSUE TITLE
[FEATURE] - Kernel

### ISSUE THREAD

**Issue by TeaqariaWTF** [zaneschepke/wgtunnel#66] opened 2023-12-07 19:52 UTC
I just discovered the app and it works great.

I would like to make a feature request

Can we add the ability to run in the background on Kernels that support it, like in the official app?

![Screenshot_20231207-224835_WireGuard](https://github.com/zaneschepke/wgtunnel/assets/90970076/90d565eb-6269-4942-8085-51dea18451b1)
![Screenshot_20231207-224842_WireGuard](https://github.com/zaneschepke/wgtunnel/assets/90970076/d0599652-b4ac-4709-a3ae-09589a2b5160)
![Screenshot_20231207-225223_KernelSU](https://github.com/zaneschepke/wgtunnel/assets/90970076/ca02a7ff-bf78-43a0-9b34-59bc17fc0e34)

**Comment by zaneschepke** [comment] 2023-12-08 00:26
Hello! This is a duplicate of #43. Please track the progress of this feature there.

**Closed by zaneschepke** 2023-12-08 00:26 UTC
Labels: enhancement
