### ISSUE TITLE
[BUG] - energy consumption of wg tunnel > 25 %

### ISSUE THREAD

**Issue by merlinuwe** [zaneschepke/wgtunnel#411] opened 2024-10-23 14:30 UTC
I use a Xiaomi Poco X3 pro with android 11.

Since the latest update, my phone gets warmer and uses more energy. Anyone else with the same issue?

**Comment by zaneschepke** [comment] 2024-10-23 14:31
Hello! Version please?

**Comment by merlinuwe** [comment] 2024-10-23 14:36
That was fast. ;-)

3.5.4

Not rooted

**Comment by Gu4n** [comment] 2024-10-24 08:32
Same issue here with version 3.5.4 on an unrooted Samsung Galaxy A54. WG Tunnel used 20.4% of the battery since the phone stopped charging 2h20m ago.

**Comment by HardWiredNZ1** [comment] 2024-10-24 11:01
Confirming 30% battery usage on Samsung S22 Ultra, even with auto connect paused and no tunnel operational for most of the day

**Comment by merlinuwe** [comment] 2024-10-24 11:57
> Confirming 30% battery usage on Samsung S22 Ultra, even with auto connect paused and no tunnel operational for most of the day, no root, stock OS, was fine last version I believe

Yes, in 3.5.3 there isn't this issue; I downgraded yesterday, now I have 15 %.

**Comment by merlinuwe** [comment] 2024-10-24 19:06
Feedback to this nightly built:

https://github.com/zaneschepke/wgtunnel/releases/download/nightly/wgtunnel-fdroid-nightly-3.5.4-2054930-nightly.apk

6,5 % Akku

**Comment by HardWiredNZ1** [comment] 2024-10-25 08:25
I switched to 3.5.2 from fdroid (previous one 3.5.4 was from Google play store) and now battery usage is down to 0.8% for the day

**Comment by Solarunit** [comment] 2024-10-27 02:57
I noticed this too >30%, but version was 3.5.3.
Looks like 3.5.2 is not affected.

**Comment by zaneschepke** [comment] 2024-10-29 02:19
I'm sorry about this one everyone. This is connected to the new feature I added in 3.5.3 to allow rooted devices to get the wifi name from the shell without using location services. 

I know the root cause of the issue and I'm working on a fix! 

Thank you all for the report.

**Comment by Solarunit** [comment] 2024-10-29 16:02
BTW on version 3.5.2 app's battery usage is about `0`, I don't even see wgtunnel in the list of apps in battery usage statistics.

**Comment by zaneschepke** [comment] 2024-11-08 22:59
Hello! This should be fixed in 3.6.0.

 Please let me know if the issue persists and we can reopen.

**Closed by zaneschepke** 2024-11-08 22:59 UTC
Labels: bug
